version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        APP_NAME: app
      target: development
    container_name: py_dev_app
    command: python3 manage.py runserver 0.0.0.0:8000
    tty: true
    stdin_open: true
    volumes:
      - .:/app:cached
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: py_dev_db
    volumes:
      - ./inits/db/:/docker-entrypoint-initdb.d
      - ./docker/db/mysql/data:/var/lib/mysql:cached
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: py_sampledb_development
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci